import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Admin Modules
  {
    path: "/admin/dashboard/main",
    title: "Dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
   /*    {
        path: "/admin/dashboard/main",
        title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD1",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }, */
  /*     {
        path: "/admin/dashboard/dashboard2",
        title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD2",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }, */
    ],
  },
  {
    path: "",
    title: "MENUITEMS.PROJECTS.TEXT",
    iconType: "feather",
    icon: "book",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "/admin/projects/allProjects",
        title: "MENUITEMS.PROJECTS.LIST.ALL-PROJECTS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/admin/projects/addProject",
        title: "MENUITEMS.PROJECTS.LIST.ADD-PROJECT",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },

    ],
  },
  {
    path: "",
    title: "MENUITEMS.EMPLOYEES.TEXT",
    iconType: "feather",
    icon: "users",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "/admin/employees/allEmployees",
        title: "MENUITEMS.EMPLOYEES.LIST.ALL-EMPLOYEE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/admin/employees/add-employee",
        title: "MENUITEMS.EMPLOYEES.LIST.ADD-EMPLOYEE",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },

    ],
  },

  {
    path: "",
    title: "MENUITEMS.CLIENTS.TEXT",
    iconType: "feather",
    icon: "user",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "/admin/clients/all-clients",
        title: "MENUITEMS.CLIENTS.LIST.ALL-CLIENTS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/admin/clients/add-client",
        title: "MENUITEMS.CLIENTS.LIST.ADD-CLIENT",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },

    ],
  },
  {
    path: "/admin/Signup-Requests",
    title: "Signup-Requests",
    iconType: "feather",
    icon: "users",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "/TeamLeader/dashboard",
    title: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Team Leader"],
    submenu: [],
  },
  {
    path: "",
    title: "tasks",
    iconType: "feather",
    icon: "check-circle",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Team Leader"],
    submenu: [
      {
        path: "/TeamLeader/tasks",
        title: "Tasks",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/TeamLeader/Mytasks",
        title: "My Taks",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },


    ],
  },
  {
    path: "/TeamLeader/proces-verbal",
    title: "proces-verbal",
    iconType: "feather",
    icon: "trello",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Team Leader"],
    submenu: [],
  },
  {
    path: "/TeamLeader/all-projects",
    title: "all-projects",
    iconType: "feather",
    icon: "book",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Team Leader"],
    submenu: [],
  },
  {
    path: "/TeamLeader/client-claims",
    title: "Client claims",
    iconType: "feather",
    icon: "file-text",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Team Leader"],
    submenu: [],
  },
  {
    path: "/TeamLeader/risk",
    title: "Risks",
    iconType: "feather",
    icon: "shield",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Team Leader"],
    submenu: [],
  },

   {
    path: "/admin/reports/reclamations",
    title: "Reclamations",
    iconType: "feather",
    icon: "file-text",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "/admin/reports/risks",
    title: "Risks",
    iconType: "feather",
    icon: "shield",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },

  // Employee Modules
  {
    path: "/employee/dashboard",
    title: "MENUITEMS.EMPLOYEE.DASHBOARD",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Engineer" ],
    submenu: [],
  },

  {
    path: "/employee/myteam",
    title: "MENUITEMS.EMPLOYEE.MYTEAM",
    iconType: "feather",
    icon: "users",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Engineer" ],
    submenu: [],
  },
  {
    path: "/employee/myprojects",
    title: "MENUITEMS.EMPLOYEE.MYPROJECTS",
    iconType: "feather",
    icon: "database",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Engineer" ],
    submenu: [],
  },
  {
    path: "/employee/mytasks",
    title: "MENUITEMS.EMPLOYEE.MYTASKS",
    iconType: "feather",
    icon: "command",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Engineer" ],
    submenu: [],
  },
  {
    path: "/employee/risk",
    title: "Risks",
    iconType: "feather",
    icon: "shield",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Engineer"],
    submenu: [],
  },

/*   {
    path: "/apps/chat",
    title: "MENUITEMS.EMPLOYEE.CHAT",
    iconType: "feather",
    icon: "message-square",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Engineer" ],
    submenu: [],
  }, */
  // Client Modules
  {
    path: "/client/dashboard",
    title: "MENUITEMS.CLIENT.DASHBOARD",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Client"],
    submenu: [],
  },
  {
    path: "/client/proces-verbal",
    title: "proces-verbal",
    iconType: "feather",
    icon: "book",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Client"],
    submenu: [],
  },
  {
    path: "/client/projects/myProjects",
    title: "MENUITEMS.CLIENT.PROJECTS.TEXT",
    iconType: "feather",
    icon: "book",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Client"],
    submenu: [
   /*    {
        path: "/client/projects/myProjects",
        title: "MENUITEMS.CLIENT.PROJECTS.LIST.MY-PROJECTS",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }, */

    ],
  },

      {
        path: "/client/supports/claims",
        title: " My reclamations",
        iconType: "",
        icon: "slack",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Client"],
        submenu: [],
      },

  {
    path: "extra-pages/profile",
    title: "profile",
    iconType: "feather",
    icon: "settings",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Client","Admin","Engineer","Team Leader"],
    submenu: [],
  },

  // Common Modules


  {
    path: "calendar",
    title: "Calendar",
    iconType: "feather",
    icon: "calendar",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-end",
    role: ["Admin", "Engineer","Team Leader"],
    submenu: [],
  },
  {
    path: "task",
    title: "Task",
    iconType: "feather",
    icon: "check-circle",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "Proces",
    title: "Proces-Verbal",
    iconType: "feather",
    icon: "trello",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin",],
    submenu: [],
  },
  {
    path: "/email/compose",
    title: "Email",
    iconType: "feather",
    icon: "mail",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },

];
